name: falltergeist # you probably want to 'snapcraft register <name>'
version: 0.3.1 # just for humans, typically '1.2+git' or '1.3.2'
summary: Open Source Fallout 2 game engine # 79 char long summary
description: |
  Opensource crossplatform Fallout 2™ engine writen in C++ and SDL. 
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
 falltergeist:
  command: falltergeist
  plugs:
  - a1sa
  - pulsadio
  - x11
  - opengl
  
parts:
  falltergiest:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/falltergeist/falltergeist/archive/0.3.1.tar.gz
    source-type: tar
    build-packages:
    - libsdl2-dev 
    - libsdl2-mixer-dev 
    - libsdl2-image-dev 
    - libglew-dev 
    - libglm-dev 
    - zlib1g-dev
